default:

  VERSION: 0.0.1

  DEBUG: False

  # dynaconf environment switcher, this is set when dynaconf is initialized
  ENVIRONMENT:

  # the secret key must be set in each environment
  SECRET_KEY:

  ALLOWED_HOSTS: []

  # add our installed apps
  INSTALLED_APPS:
    - django.contrib.admin
    - django.contrib.auth
    - django.contrib.contenttypes
    - django.contrib.sessions
    - django.contrib.messages
    - django.contrib.staticfiles
    - app.apps.AppConfig
    - rest_framework
    - django_celery_beat

  MIDDLEWARE:
    - django.middleware.security.SecurityMiddleware
    - django.contrib.sessions.middleware.SessionMiddleware
    - django.middleware.common.CommonMiddleware
    - django.middleware.csrf.CsrfViewMiddleware
    - django.contrib.auth.middleware.AuthenticationMiddleware
    - django.contrib.messages.middleware.MessageMiddleware
    - django.middleware.clickjacking.XFrameOptionsMiddleware

  ROOT_URLCONF: project.urls

  # standard Django configuration
  TEMPLATES:
    - BACKEND: django.template.backends.django.DjangoTemplates
      DIRS: [ ]
      APP_DIRS: True
      OPTIONS:
        context_processors:
          - django.template.context_processors.debug
          - django.template.context_processors.media
          - django.template.context_processors.request
          - django.contrib.auth.context_processors.auth
          - django.contrib.messages.context_processors.messages

  # Password validation
  # https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators
  AUTH_PASSWORD_VALIDATORS:
    - NAME: django.contrib.auth.password_validation.UserAttributeSimilarityValidator
    - NAME: django.contrib.auth.password_validation.MinimumLengthValidator
    - NAME: django.contrib.auth.password_validation.CommonPasswordValidator
    - NAME: django.contrib.auth.password_validation.NumericPasswordValidator

  WSGI_APPLICATION: project.wsgi.application

  LANGUAGE_CODE: en-us
  TIME_ZONE: UTC
  USE_I18N: True
  USE_L10N: True
  USE_TZ: True

  # standard Django configuration
  STATIC_URL: /static/
  STATIC_ROOT:

  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql
      HOST: postgres
      NAME: postgres
      USER: postgres
      PASSWORD: postgres
      PORT: 5432

  # Celery settings

  #: Only add pickle to this list if your broker is secured
  #: from unwanted access (see userguide/security.html)
  CELERY_ACCEPT_CONTENT: ['json']
  CELERY_TASK_SERIALIZER: json

  # use Redis as broker
  CELERY_BROKER_URL:
  # use Redis as result backend
  CELERY_RESULT_BACKEND:
  CELERY_RESULT_EXPIRES: 3600
  CELERY_TASK_DEFAULT_QUEUE: default
#  CELERY_TASK_ROUTES:
#    tasks.tasks.portfolio_rebalance:
#      queue: prive
#    tasks.tasks.test_queue:
#      queue: prive


development:
  DEBUG: True
  SECRET_KEY: DEV-ENVIRONMENT-SECRET-KEY
  ALLOWED_HOSTS:
    - localhost
    - 127.0.0.1

testing:
  DEBUG: True
  SECRET_KEY: TEST-ENVIRONMENT-SECRET-KEY
  ALLOWED_HOSTS:
    - localhost
    - 127.0.0.1